name: w_gen
description: A sample command-line application.
version: 0.0.4
# homepage: https://www.example.com

environment:
  sdk: '>=2.17.6 <3.0.0'

# dependencies:
#   path: ^1.8.0

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0
dependencies: {args: ^2.3.1, http: ^0.13.5, path: ^1.8.2, rxdart: ^0.27.5}
